### ISSUE TITLE
build errors and missing presets for android sample project

### ISSUE THREAD

**Issue by dkanada** [projectM-visualizer/examples-android#1]
On a fresh clone I get the following errors when trying to build for Android.

```
FileScanner.cpp:150:18: error: use of undeclared identifier 'fts_open'
FileScanner.cpp:164:20: error: use of undeclared identifier 'fts_read'
FileScanner.cpp:184:5: error: use of undeclared identifier 'fts_close'
FileScanner.cpp:184:15: error: cannot initialize a parameter of type 'FILE *' with an lvalue of type 'FTS *'
```

I used these commands in different configurations to actually build the library.

```
./autogen.sh
./configure-ndk

make
make install-strip
```

As mentioned in projectM-visualizer/projectm#444 I tried running `./configure` before `./configure-ndk` which had no effect on the errors. I also tried inverting the `HAVE_FTS_H` compile flags in `FileScanner.cpp` since that was also referenced, which technically fixes the build. However, the sample app refuses to pick up any presets, and I have a hunch the FileScanner changes are to blame. The `fts.h` file seems to be found when `./configure-ndk` is run so I'm not sure what is going on here. Another related issue might be projectM-visualizer/projectm#396 since it has at least one similar error message.

```
./configure-ndk
[...]
checking for fts.h... yes
[...]
```

I was able to confirm the presets exist within the cache directory. In fact, it seems like the new preset directory structure has issues on Android, which doesn't properly handle the subfolders and needed changes to work properly. I also tried filtering out all files without the `.milk` prefix during asset extraction, which had no effect.

**Comment by nzoschke** [comment]
I got this to build on an M1 Mac and run on a Kindle Fire HD 10. It took a lot of googling for error messages and guessing at various versions of NDK, Gradle etc. Some breadcrumbs for anyone else...

Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on September 30, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64

In Tools -> SDK Manager -> SDK Tools

- Check "Show Package Details"
- Install NDK 24.0.8215888
- Install CMake 3.10.2.4988404

Apply these diffs

```diff
diff --git a/app/build.gradle b/app/build.gradle
index 6c98870..39e4157 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -31,11 +31,12 @@ android {
     }
     sourceSets {
         main {
-            jniLibs.srcDirs 'jniLibs', 'jniLibs/armeabi-v7a'
+//            jniLibs.srcDirs 'jniLibs', 'jniLibs/armeabi-v7a'
         }
     }
     productFlavors {
     }
+    ndkVersion '24.0.8215888'
 }
 dependencies {
     implementation fileTree(include: ['*.jar'], dir: 'libs')
diff --git a/build.gradle b/build.gradle
index 6942f5e..35abed4 100644
--- a/build.gradle
+++ b/build.gradle
@@ -7,7 +7,7 @@ buildscript {
 
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.3.2'
+        classpath 'com.android.tools.build:gradle:4.2.2'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 5974ea3..391c0d5 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
diff --git a/local.properties b/local.properties
new file mode 100644
index 0000000..19ea332
--- /dev/null
+++ b/local.properties
@@ -0,0 +1,9 @@
+## This file must *NOT* be checked into Version Control Systems,
+# as it contains information specific to your local configuration.
+#
+# Location of the SDK. This is only used by Gradle.
+# For customization when using a Version Control System, please read the
+# header note.
+#Fri May 06 21:40:39 PDT 2022
+sdk.dir=/Users/noah/Library/Android/sdk
+ndk.dir=/Users/noah/Library/Android/sdk/ndk/24.0.8215888
```

In File -> Project Structure I see

- Android Gradle Plugin Version: 4.2.2
- Gradle Version: 7.4.2
- Android NDK location: /Users/me/Library/Android/sdk/ndk/24.0.8215888
